# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json

  # JavaScript/HTML hooks
  - repo: https://github.com/biomejs/pre-commit
    # full list of options here: https://biomejs.dev/reference/configuration
    rev: "v0.1.0"
    hooks:
    -   id: biome-format
        additional_dependencies: ["@biomejs/biome@1.8.3"]

  # Python hooks
  - repo: https://github.com/psf/black-pre-commit-mirror
    # full list of options here: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
    # add any rules in the 'args' list : "args : ['l 100']" for a line length of 100
    rev: 24.2.0
    hooks:
    -   id: black
        args: ['-l 110']
